-- MySQL Script generated by MySQL Workbench
-- Sat Jan 29 23:45:19 2022
-- Model: DFMS    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DFMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DFMS` ;

-- -----------------------------------------------------
-- Schema DFMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DFMS` DEFAULT CHARACTER SET utf8 ;
USE `DFMS` ;

-- -----------------------------------------------------
-- Table `DFMS`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `login` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template_group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(8) NOT NULL,
  `privacy_level` INT NOT NULL DEFAULT 0,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_group_parent_idx` (`parent_id` ASC),
  CONSTRAINT `fk_ftg_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `DFMS`.`form.template_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `group_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `reference_number_pattern` VARCHAR(32) NOT NULL,
  `published_version` INT UNSIGNED NULL,
  `privacy_level` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_template_group_idx` (`group_id` ASC),
  INDEX `guid_idx` (`published_version` ASC),
  CONSTRAINT `fk_ft_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `DFMS`.`form.template_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_definition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`title` ASC),
  UNIQUE INDEX `type_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template_version` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `template_id` INT UNSIGNED NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  `columns` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_template_version_template_idx` (`template_id` ASC),
  CONSTRAINT `fk_ftv_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template_section` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `template_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(256) NULL,
  `sequence` INT UNSIGNED NOT NULL,
  `outer_columns` INT UNSIGNED NOT NULL DEFAULT 1,
  `inner_columns` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_template_section_template_idx` (`template_id` ASC),
  CONSTRAINT `fk_fts_template_version`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(64) NOT NULL,
  `template_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_field_group_template_id_idx` (`template_id` ASC),
  CONSTRAINT `fk_ffg_template_id`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.value_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.value_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`code` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template_field` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(128) NOT NULL,
  `code` VARCHAR(32) NULL,
  `description` VARCHAR(4000) NULL,
  `sequence` INT UNSIGNED NOT NULL,
  `field_definition_id` INT UNSIGNED NOT NULL,
  `template_section_id` INT UNSIGNED NOT NULL,
  `field_group_id` INT UNSIGNED NULL,
  `value_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_field_definition_idx` (`field_definition_id` ASC),
  INDEX `fk_template_field_group_id_idx` (`field_group_id` ASC),
  INDEX `fk_template_field_section_idx` (`template_section_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `fk_template_field_value_type_idx` (`value_type_id` ASC),
  CONSTRAINT `fk_ftf_field_definition`
    FOREIGN KEY (`field_definition_id`)
    REFERENCES `DFMS`.`form.field_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ftf_template_section`
    FOREIGN KEY (`template_section_id`)
    REFERENCES `DFMS`.`form.template_section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ftf_field_group`
    FOREIGN KEY (`field_group_id`)
    REFERENCES `DFMS`.`form.field_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ftf_value_type`
    FOREIGN KEY (`value_type_id`)
    REFERENCES `DFMS`.`form.value_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.form_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.form_instance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `reference_number` VARCHAR(16) NOT NULL,
  `template_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`reference_number` ASC),
  INDEX `fk_form_instance_template_idx` (`template_id` ASC),
  CONSTRAINT `fk_ffi_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `field_id` INT UNSIGNED NOT NULL,
  `form_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  `string` VARCHAR(4000) NULL,
  `boolean` TINYINT(1) NULL,
  `integer` INT NULL,
  `decimal` DECIMAL(9,3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_data_field_idx` (`field_id` ASC),
  INDEX `fk_field_value_form_instance_idx` (`form_id` ASC),
  CONSTRAINT `fk_ffv_field`
    FOREIGN KEY (`field_id`)
    REFERENCES `DFMS`.`form.template_field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ffv_form`
    FOREIGN KEY (`form_id`)
    REFERENCES `DFMS`.`form.form_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`dictionary` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `value` VARCHAR(45) NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dictionary_parent_idx` (`parent_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_d_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `DFMS`.`dictionary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_definition_value_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_definition_value_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `field_definition_id` INT UNSIGNED NOT NULL,
  `value_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_definition_value_type_idx` (`value_type_id` ASC),
  INDEX `fk_field_definition_value_type_field_idx` (`field_definition_id` ASC),
  CONSTRAINT `fk_ffdvt_value_type`
    FOREIGN KEY (`value_type_id`)
    REFERENCES `DFMS`.`form.value_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ffdvt_field_definition`
    FOREIGN KEY (`field_definition_id`)
    REFERENCES `DFMS`.`form.field_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.predefinied_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.predefinied_field` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `base_definition_id` INT UNSIGNED NOT NULL,
  `value_type_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `global` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_predefinied_field_base_definition_idx` (`base_definition_id` ASC),
  INDEX `fk_predefinied_field_value_type_idx` (`value_type_id` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  CONSTRAINT `fk_fpf_field_definition`
    FOREIGN KEY (`base_definition_id`)
    REFERENCES `DFMS`.`form.field_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fpf_value_type`
    FOREIGN KEY (`value_type_id`)
    REFERENCES `DFMS`.`form.value_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_option` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `template_field_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  `string` VARCHAR(4000) NULL,
  `boolean` TINYINT(1) NULL,
  `integer` INT NULL,
  `decimal` DECIMAL(9,3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_data_field_idx` (`template_field_id` ASC),
  CONSTRAINT `fk_ffo_template_field`
    FOREIGN KEY (`template_field_id`)
    REFERENCES `DFMS`.`form.template_field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.predefinied_field_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.predefinied_field_option` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `predefinied_field_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  `string` VARCHAR(4000) NULL,
  `boolean` TINYINT(1) NULL,
  `integer` INT NULL,
  `decimal` DECIMAL(9,3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_predefinied_option_field_idx` (`predefinied_field_id` ASC),
  CONSTRAINT `fk_fpfo_predefinied_field`
    FOREIGN KEY (`predefinied_field_id`)
    REFERENCES `DFMS`.`form.predefinied_field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`user.group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`user.group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`user.group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`user.group_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `group_id` INT UNSIGNED NOT NULL,
  `user_login` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_user_group_idx` (`group_id` ASC),
  CONSTRAINT `fk_ugu_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `DFMS`.`user.group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.visibility_rule_expression_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.visibility_rule_expression_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(32) NOT NULL,
  `description` VARCHAR(256) NULL,
  `value` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.visibility_rule_expression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.visibility_rule_expression` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `parent_id` INT UNSIGNED NULL,
  `type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_visibility_rule_expresion_parent_idx` (`parent_id` ASC),
  INDEX `fk_visibility_rule_expression_type_idx` (`type_id` ASC),
  CONSTRAINT `fk_fvre_visibility_rule_expresion`
    FOREIGN KEY (`parent_id`)
    REFERENCES `DFMS`.`form.visibility_rule_expression` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fvre_visibility_rule_expression_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `DFMS`.`form.visibility_rule_expression_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.visibility_rule_definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.visibility_rule_definition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(64) NOT NULL,
  `expression_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visibility_rule_definition_expression_idx` (`expression_id` ASC),
  CONSTRAINT `fk_fvrd_visibility_rule_expression`
    FOREIGN KEY (`expression_id`)
    REFERENCES `DFMS`.`form.visibility_rule_expression` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_section_visibility_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_section_visibility_rule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `field_id` INT UNSIGNED NULL,
  `section_id` INT UNSIGNED NULL,
  `rule_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visibility_rule_idx` (`rule_id` ASC),
  INDEX `fk_section_visibility_rule_idx` (`section_id` ASC),
  INDEX `fk_field_visibility_rule_idx` (`field_id` ASC),
  CONSTRAINT `fk_ffsvr_template_field`
    FOREIGN KEY (`field_id`)
    REFERENCES `DFMS`.`form.template_field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ffsvr_template_seciton`
    FOREIGN KEY (`section_id`)
    REFERENCES `DFMS`.`form.template_section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ffsvr_visibility_rule_definition`
    FOREIGN KEY (`rule_id`)
    REFERENCES `DFMS`.`form.visibility_rule_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.visibility_rule_operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.visibility_rule_operator` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(32) NOT NULL,
  `description` VARCHAR(256) NULL,
  `value` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.visibility_rule_phrase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.visibility_rule_phrase` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `expression_id` INT UNSIGNED NOT NULL,
  `field_id` INT UNSIGNED NOT NULL,
  `operator_id` INT UNSIGNED NOT NULL,
  `option_id` INT UNSIGNED NULL,
  `value` DECIMAL(9,3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visibility_rule_phrase_expression_idx` (`expression_id` ASC),
  INDEX `fk_visibility_rule_phrase_option_idx` (`option_id` ASC),
  INDEX `fk_visibility_rule_phrase_operator_idx` (`operator_id` ASC),
  CONSTRAINT `fk_fvrp_visibility_rule_expression`
    FOREIGN KEY (`expression_id`)
    REFERENCES `DFMS`.`form.visibility_rule_expression` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fvrp_visibility_rule_operator`
    FOREIGN KEY (`operator_id`)
    REFERENCES `DFMS`.`form.visibility_rule_operator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fvrp_field_option`
    FOREIGN KEY (`option_id`)
    REFERENCES `DFMS`.`form.field_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.template_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.template_access` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `template_group_id` INT UNSIGNED NULL,
  `template_id` INT UNSIGNED NULL,
  `user_group_id` INT UNSIGNED NULL,
  `user_login` VARCHAR(32) NULL,
  `view` TINYINT(1) NOT NULL DEFAULT 0,
  `edit` TINYINT(1) NOT NULL DEFAULT 0,
  `delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_template_access_template_group_idx` (`template_group_id` ASC),
  INDEX `fk_template_access_template_idx` (`template_id` ASC),
  INDEX `fk_template_access_user_group_idx` (`user_group_id` ASC),
  CONSTRAINT `fk_fta_template_group`
    FOREIGN KEY (`template_group_id`)
    REFERENCES `DFMS`.`form.template_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fta_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fta_user_group`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `DFMS`.`user.group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.favourite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.favourite` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `template_id` INT UNSIGNED NOT NULL,
  `sequence` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favourite_template_idx` (`template_id` ASC),
  CONSTRAINT `fk_ff_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `DFMS`.`form.template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.validation_rule_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.validation_rule_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `code` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.validation_rule_definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.validation_rule_definition` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `title` VARCHAR(64) NOT NULL,
  `validation_type_id` INT UNSIGNED NOT NULL,
  `default_value` VARCHAR(256) NULL,
  `default_message` VARCHAR(256) NULL,
  `editable_value` TINYINT(1) NOT NULL DEFAULT 1,
  `editable_message` TINYINT(1) NOT NULL DEFAULT 1,
  `global` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`title` ASC),
  INDEX `fk_validation_rule_type_idx` (`validation_type_id` ASC),
  CONSTRAINT `fk_vrd_validation_rule_type`
    FOREIGN KEY (`validation_type_id`)
    REFERENCES `DFMS`.`form.validation_rule_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.validation_rule_value_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.validation_rule_value_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `value_type_id` INT UNSIGNED NOT NULL,
  `validation_definition_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_validation_rule_type_idx` (`value_type_id` ASC),
  INDEX `fk_validation_rule_definition_idx` (`validation_definition_id` ASC),
  CONSTRAINT `fk_fvrvt_value_type`
    FOREIGN KEY (`value_type_id`)
    REFERENCES `DFMS`.`form.value_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fvrvt_validation_rule_definition`
    FOREIGN KEY (`validation_definition_id`)
    REFERENCES `DFMS`.`form.validation_rule_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DFMS`.`form.field_validation_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DFMS`.`form.field_validation_rule` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `add_login` VARCHAR(32) NOT NULL,
  `add_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modif_login` VARCHAR(32) NULL,
  `modif_date` TIMESTAMP(6) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `field_id` INT UNSIGNED NOT NULL,
  `validation_rule_id` INT UNSIGNED NOT NULL,
  `value` VARCHAR(256) NULL,
  `message` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_validation_definition_idx` (`validation_rule_id` ASC),
  INDEX `fk_field_validation_field_idx` (`field_id` ASC),
  CONSTRAINT `fk_ffvr_template_field`
    FOREIGN KEY (`field_id`)
    REFERENCES `DFMS`.`form.template_field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ffvr_validation_rule_definition`
    FOREIGN KEY (`validation_rule_id`)
    REFERENCES `DFMS`.`form.validation_rule_definition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DFMS`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`user` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `login`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Krzaczek');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.field_definition`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (1, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Pole tekstowe', 'TEXT', 0);
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (2, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wielowierszowe pole tekstowe', 'TEXT-AREA', 0);
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (3, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Lista wielokrotnego wyboru', 'CHECKBOX-GROUP', 1);
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (4, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Lista pojedynczego wyboru', 'RADIO', 1);
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (5, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Lista wybieralna', 'SELECT', 1);
INSERT INTO `DFMS`.`form.field_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`, `visible`) VALUES (6, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Pole wyboru', 'CHECKBOX', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.value_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`) VALUES (1, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Ciąg znaków', 'STRING');
INSERT INTO `DFMS`.`form.value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`) VALUES (2, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Data', 'DATE');
INSERT INTO `DFMS`.`form.value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`) VALUES (3, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Tak/Nie', 'BOOLEAN');
INSERT INTO `DFMS`.`form.value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`) VALUES (4, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Liczba całkowita', 'NUMBER');
INSERT INTO `DFMS`.`form.value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `code`) VALUES (5, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Liczba rzeczywista', 'DECIMAL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`dictionary`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (1, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'REF_NUMBER_PATTERN_CODES', 'Słowa kluczowe nr referencyjnych formularzy', NULL, NULL);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'TEMPLATE_VERSION', 'Wersja szablonu formularza', NULL, 1);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'TEMPLATE_NAME', 'Nazwa formularza', NULL, 1);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'YEAR', 'Aktualny rok', NULL, 1);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'MONTH', 'Aktualny miesiąc', NULL, 1);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'DAY', 'Aktualny dzień', NULL, 1);
INSERT INTO `DFMS`.`dictionary` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `name`, `description`, `value`, `parent_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'GROUP_CODE', 'Kod grupy formularzy', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.field_definition_value_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 1);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 2);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 4);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 5);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 2, 1);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 3, 1);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 3, 2);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 3, 4);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 3, 5);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 4, 1);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 4, 2);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 4, 4);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 4, 5);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 5, 1);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 5, 2);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 5, 4);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 5, 5);
INSERT INTO `DFMS`.`form.field_definition_value_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `field_definition_id`, `value_type_id`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 6, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.predefinied_field`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 1, 'Pole tekstowe', 1);
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 3, 'Data', 1);
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 4, 'Liczba całkowita', 1);
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 1, 5, 'Liczba rzeczywista', 1);
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 2, 1, 'Wielowierszowe pole tekstowe', 1);
INSERT INTO `DFMS`.`form.predefinied_field` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `base_definition_id`, `value_type_id`, `title`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 6, 3, 'Pole wyboru', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.visibility_rule_expression_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.visibility_rule_expression_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'lub', NULL, 'DISJUNCTION');
INSERT INTO `DFMS`.`form.visibility_rule_expression_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'oraz', NULL, 'CONJUNCTION');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.visibility_rule_operator`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Pole jest puste', NULL, 'IS_EMPTY');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Pole nie jest puste', NULL, 'IS_NOT_EMPTY');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola mniejsza niż', NULL, 'LESSER_THAN');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola nie mniejsza niż', NULL, 'NOT_LESSER_THAN');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola większa niż', NULL, 'GREATER_THAN');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola nie większa niż', NULL, 'NOT_GREATER_THAN');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola równa', NULL, 'EQUAL_TO');
INSERT INTO `DFMS`.`form.visibility_rule_operator` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `description`, `value`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wartość pola inna niż', NULL, 'NOT_EQUAL_TO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.validation_rule_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (1, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'REQUIRED');
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (2, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'MIN_LENGTH');
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (3, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'MAX_LENGTH');
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (4, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'MIN_VALUE');
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (5, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'MAX_VALUE');
INSERT INTO `DFMS`.`form.validation_rule_type` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `code`) VALUES (6, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'REGEX');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DFMS`.`form.validation_rule_definition`
-- -----------------------------------------------------
START TRANSACTION;
USE `DFMS`;
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Pole wymagane', 1, NULL, 'Pole obowiązkowe', 0, 1, DEFAULT);
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Minimalna długość', 2, '3', 'Wprowadzony tekst jest zbyt krótki', 1, 1, DEFAULT);
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Maksymalna długość', 3, '100', 'Wprowadzony tekst jest zbyt długi', 1, 1, DEFAULT);
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Minimalna wartość', 4, NULL, 'Wprowadzona wartość jest zbyt mała', 1, 1, DEFAULT);
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Maksymalna wartość', 5, NULL, 'Wprowadzona wartość jest zbyt duża', 1, 1, DEFAULT);
INSERT INTO `DFMS`.`form.validation_rule_definition` (`id`, `add_login`, `add_date`, `modif_login`, `modif_date`, `active`, `title`, `validation_type_id`, `default_value`, `default_message`, `editable_value`, `editable_message`, `global`) VALUES (DEFAULT, 'CREATE_SCRIPT', DEFAULT, NULL, NULL, DEFAULT, 'Wyrażenie regularne', 6, '^.*$', 'Wprowadzony tekst ma zły format', 1, 1, DEFAULT);

COMMIT;

